# FROM python:3.10-bullseye
# RUN python -m pip install --upgrade pip

# ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
# RUN chmod +x /wait

# WORKDIR /app
# COPY requirements.txt requirements.txt
# RUN python -m pip install -r requirements.txt

# CMD /wait && uvicorn main:app --reload --host 0.0.0.0


FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
WORKDIR /app

# Copy the top-level files
COPY requirements.txt requirements.txt
COPY main.py main.py

# Copy all of the directories that contain your application
# code
COPY api api
COPY ghi ghi

RUN pip install -r requirements.txt
CMD uvicorn main:app --reload --host 0.0.0.0 --port $PORT
